### ISSUE TITLE
MySQL slave does not get promoted to master?

### ISSUE THREAD

**Issue by JokerQyou** [chenqiangzhishen/docker-mysql-master-slave-ha#1]
I'm a total newbie in the clustering and HA field, and I want to ask something after reading the source code of this repo.

Say if I deploy an environment with your solution, there will be a MySQL master container (with a keepalived container) on machine A, and a MySQL slave container (with a keepalived container) on machine B.

So:
- MySQL B will sync data from MySQL A.
- MySQL A provides both read and write support.
- MySQL B provides only read support, unless explicitly promoted to a master.

The VIP stays on machine A in normal state.

If keepalived A is cut off from the network (or MySQL A goes down), it gets demoted, and the VIP gets shifted to machine B.

So at this point, my application using the VIP will start perform both read and write operations on MySQL B. But MySQL B is always a slave node, which means it's read only.

The question is, how can I promote the target MySQL slave to a master after shifting the VIP? As far as I understand, this is not possible with `solnetcloud/keepalived` image, is that right?

**Comment by JokerQyou** [comment]
I've modified the keepalived image (based on `solnetcloud/keepalived`) to support `notify_master`, `notify_backup` and `notify_fault` scripts, so it is possible to do automated MySQL master failover in these scripts.

**Comment by chenqiangzhishen** [comment]
good, welcome to check in your codes..
